language: ruby
rvm:
- 2.1.1
branches:
  only:
  - master
env:
- TEST_SUITE=rspec RAILS_VERSION=4.1.9
- TEST_SUITE=cucumber RAILS_VERSION=4.1.9
script:
- bundle exec rake app:transam_cpt:prepare_rspec
- bundle exec $TEST_SUITE
before_script:
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
before_install:
- openssl aes-256-cbc -K $encrypted_197ddf04b7cf_key -iv $encrypted_197ddf04b7cf_iv
  -in schema.rb.enc -out schema.rb -d
