language: ruby
rvm:
- 2.1.1
branches:
  only:
  - master
env:
- TEST_SUITE=rspec
- TEST_SUITE=cucumber
script:
- bundle exec rake app:transam_cpt:prepare_rspec
- bundle exec $TEST_SUITE
before_install:
- openssl aes-256-cbc -K $encrypted_b617358ced91_key -iv $encrypted_b617358ced91_iv
  -in spec/dummy/db/schema.rb.enc -out spec/dummy/db/schema.rb -d
