language: ruby
rvm:
- 2.2.2
branches:
  only:
  - master
before_script:
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
before_install:
- mysql -e "create database IF NOT EXISTS transam_cpt_testing;" -uroot
script:
- bundle exec rake app:transam_cpt:prepare_rspec
- bundle exec rspec
